version: '3.8'
services:
  
  fastapi-air-radar:
    
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    volumes:
      - .:/app

    environment:
      - FASTAPI_ENV=development
      
    command: uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
